version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: datapipelinemini
      MYSQL_PORT_3306_TCP_ADDR: mysql
      